### ISSUE TITLE
IllegalState Failed to load ApplicationContext

### ISSUE THREAD

**Issue by janreyho** [robharrop/spring-angularjs#2]
Results :

Tests in error:
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext

Tests run: 16, Failures: 0, Errors: 6, Skipped: 0

**Comment by anarvaez292** [comment]
I ran all tests with SDK 1.7 successfully.
